//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AngularDemoApp.Models;

namespace AngularDemoApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student :IStudent
    {
        public int ID { get; set; }
        public System.Guid StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string VersionUser { get; set; }
        public System.DateTime VersionDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
